mystr = "Abcd Pq R Xyzw Uvw"
# print(len(mystr))
# print(mystr[0:19])
# print(mystr[0:19:3])
# print(mystr[0::2])
# print(mystr[:19:2])
# print(mystr[0:19:])
# print(mystr[-4:-2])
# print(mystr[::-2])
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("Uvw"))
print(mystr.count("A"))
print(mystr.capitalize())
print(mystr.find("Pq"))
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("Ab","Pq"))