print("*************************************************************")
a=int(input("enter value of a: "))
b=int(input("enter value of b: "))
print(type(a))
print(type(b))
print("addition = ",(a+b))
print("subtraction = ",(a-b))
print("division = ",(a/b))
print("multiplication = ",(a-b))
print("*"*60)